#!/usr/bin/env bash

set -euo pipefail

print_usage_and_exit() {
  echo "Usage: $0 PANE_ID"
  exit 1
}

if [[ $# -lt 1 ]]; then
  print_usage_and_exit
fi

pane_id=$1
if ! [[ $pane_id =~ %[0-9]+ ]]; then
  print_usage_and_exit
fi

watch_pid=$(tmux show-options -g -v -q @watch-pid-${pane_id})
if [[ -z "$watch_pid" ]]; then
  # nothing to kill, but don't bother telling the user about it
  exit 0
fi

kill $watch_pid
exit 0
