#!/usr/bin/env bash

set -euo pipefail

# SIGTERM is sent via tmux-watch-unwatch, exit with 0 prevents tmux from showing message in copy mode
trap "exit 0" SIGTERM

print_usage_and_exit() {
  echo "Usage: $0 PANE_ID COMMAND [ARGS]"
  exit 1
}

if [[ $# -lt 2 ]]; then
  print_usage_and_exit
fi

pane_id=$1
shift
user_command=$1
shift
# the rest ( $@ ) are arguments to the user command

if ! [[ $pane_id =~ %[0-9]+ ]]; then
  print_usage_and_exit
fi

# check if this pane is watched already
watch_pid=$(tmux show-options -g -v -q @watch-pid-${pane_id})
if [[ -n "$watch_pid" ]]; then
  echo "tmux-watch is already watching this pane"
  exit 1
fi
# record the watch PID, register cleanup trap
tmux set-option -g @watch-pid-${pane_id} "$$"
function cleanup {
  tmux set-option -g -u @watch-pid-${pane_id}
}
trap cleanup EXIT

set +e

while true
do
  tmux list-panes -a -F '#{pane_id}' | grep "$pane_id" &> /dev/null
  if [[ $? -ne 0 ]]; then
    # the pane we are watching is gone, so stop watching
    break
  fi

  $user_command -p $pane_id "$@"
  if [[ $? -ne 0 ]]; then
    break
  fi

  # TODO: make sleep length configurable as `watch` does
  sleep 5
done

exit 0
